### ISSUE TITLE
Add license?

### ISSUE THREAD

**Issue by Chris660** [kellda/rzif#1]
Hi, I stumbled across rzif yesterday, and it looks like it might be a good fit for a personal project of mine, but I notice there's no license information in the repo.

Would you consider releasing the code under a free/open source license (e.g. MIT/BSD/GPL)?

**Comment by kellda** [comment]
Wow my project even got enough interest to be asked a license. I'll license it under MIT, just let me time to push a commit.

**Comment by kellda** [comment]
Done

**Comment by Chris660** [comment]
Marvellous, thanks for the quick response!

BTW, I noticed a small typo in the Github project *"About"*:

> Rust Z-machine Interactive **Firction** interpreter

**Comment by kellda** [comment]
Right, thank you
